# mkdocs.yml
site_name: N2 Pairs Trader Docs

theme:
  name: "material"
  custom_dir: "docs/n2_custom_theme"
  logo: "img/logo-96px.png"
  palette:
    primary: 'black'
    accent: 'dark blue'

extra_css: 
- css/dark_theme.css
- css/codehilite.css
- css/profont.css

plugins:
- search
- mkdocstrings

nav:
  - Readme: 'index.md'
  - How it works: 
      - 1. Start the Bot: how_it_works/1_start_the_bot.md
      - 2. Initialize Strategy: how_it_works/2_initialize_strategy.md
      - 3. After Initialization: how_it_works/3_after_strategy_is_initialized.md
      - 4. Opening a Position: how_it_works/4_opening_a_position.md
      - 5. Opening a Position: how_it_works/5_closing_a_position.md
      - 6. Generating Reports: how_it_works/6_generating_reports.md
      - 7. Further Ideas: how_it_works/7_further_ideas.md
  - Creating a new strategy: 'creating_a_new_strategy.md'

edit_uri: '#docs/'

markdown_extensions:
  - codehilite
