# mkdocs.yml
site_name: N2 Pairs Trader Docs

theme:
  name: "material"
  custom_dir: "docs/n2_custom_theme"
  logo: "img/logo-96px.png"
  palette:
    primary: 'black'
    accent: 'dark blue'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra_css: 
- css/dark_theme.css
- css/codehilite.css
- css/profont.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tablesort.js


plugins:
- search
- mkdocstrings

nav:
  - Readme: 'index.md'
  - Objectives & Requirements: 'objectives_&_requirements.md'
  - How it works: 
      - 1. Start the Bot: how_it_works/1_start_the_bot.md
      - 2. Initialize Strategy: how_it_works/2_initialize_strategy.md
      - 3. Market Data & Signals: how_it_works/3_signals.md
      - 4. Opening a Position: how_it_works/4_opening_a_position.md
      - 5. Closing a Position: how_it_works/5_closing_a_position.md
      - 6. Generating Reports: how_it_works/6_generating_reports.md
      - 7. TODO: how_it_works/7_todo.md 
  - KuCoin Extended: 'KuCoin_Extended.md'
  - Creating a New Strategy: 'creating_a_new_strategy.md'
  - CCXT Insights:
      - Overview: 'ccxt_insights/1_overview.md'
      - Exchanges with margin: 'ccxt_insights/2_exchanges_with_margin.md'
      - Exchanges with fetchBorrowRate: 'ccxt_insights/3_exchanges_with_fetchBorrowRate.md'
  - Further Ideas: further_ideas.md
  - Questions, Feedback & Notes: notes.md


edit_uri: '#docs/'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  # - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
